name: CI/CD

permissions:
    id-token: write
    contents: read


on:
    push:
        branches: 
            - main

jobs: 
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: node
              uses: actions/setup-node@v3
              with:
                    node-version: 'latest'
            -   name: dependency
                run: npm install 
                
            -   name: aws-login
                uses: aws-action/configure-aws-credentials@v2
                with:
                    role-to-assume: arn:aws:iam::312356219605:role/github1
                    aws-region: ap-south-1
                    