name: CI/CD
on:
    push:
        branches: 
            -   main
            
jobs: 
    build:
        runs-on: ubuntu-latest

        steps:
            -  uses: actions/checkout@v4

            -   name: node
                uses: actions/setup-node@v3
                with:
                    node-version: 'latest'
            -   name: dependency
                run: npm install

            -

