name: CI/CD

permissions:
    id-token: write
    contents: read


on:
    push:
        branches: 
            - main

jobs: 
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: node
              uses: actions/setup-node@v3
              with:
                    node-version: 'latest'
            -   name: dependency
                run: npm install 
                
            -   name: Login  
                uses: docker/login-action@v1
                with:
                    username: ${{ secrets.USERNAME }}
                    password: ${{ secrets.PASSWORD }}

            -   name: build
                uses: docker build -t rkatrap/terra .

            -   name: push
                uses: docker push rkatrap/terra:latest
                
