name: CI/CD

permissions:
    id-token: write
    contents: read


on:
    push:
        branches: 
            - main

jobs: 
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: node
              uses: actions/setup-node@v3
              with:
                    node-version: 'latest'
            -   name: dependency
                run: npm install 
                
            -   name: aws-login
                uses: aws-actions/configure-aws-credentials@v1
                with:
                    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                    aws-region: ap-south-1

            -   name: ECR login
                id: login-ecr
                uses: aws-actions/amazon-ecr-login@v2

            -   name: Build, tag, and push Docker image to Amazon ECR
                env:
                    ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
                    ECR_REPOSITORY: my-repo
                    IMAGE_TAG: latest
                run: |
                        docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
                        docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
                        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG


            -   name: terraform
                uses: hashicorp/setup-terraform@v3

            -   name: cd 
                run: cd terraform/


            -   name:  init
                run: terraform init 


            -   name:  plan
                run: terraform plan

           # -   name: apply
            #    run: terraform apply