name: CI/CD

permissions:
    id-token: write
    contents: read


on:
    push:
        branches: 
            - main

jobs: 
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: node
              uses: actions/setup-node@v3
              with:
                    node-version: 'latest'
            -   name: dependency
                run: npm install 
                
            -   name: aws-login
                uses: aws-action/configure-aws-credentials@v1
                with:
                    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                    aws-region: us-east-1
                    
                    