name: CI/CD
on:
    push:
        branches: 
            - main

jobs: 
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: node
              uses: actions/setup-node@v3
              with:
                    node-version: 'latest'
            -   name: dependency
                run: npm install 

            -   name: aws 
                uses: aws-actions/configure-aws-credentials@v4
                with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ap-south-1

           # -   name: login ECR
            #    run:  aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $AWS_ID.dkr.ecr.ap-south-1.amazonaws.com

            
